### ISSUE TITLE
Duplicate spyglasses on search bar

### ISSUE THREAD

**Issue by mbrakken** [ABREPR/cipp#55]
![screen shot 2013-09-14 at 1 41 10 pm](https://f.cloud.github.com/assets/1530955/1144059/5f357a40-1d6d-11e3-8921-f270927f6ebf.png)

In dkan_sitewide_demo_front.module, hook_form_alter on line 90 replaces search form submit with a light grey spyglass if 

``` php
if ($form_id == 'views_exposed_filter" && $form['#id'] == 'views-exposed-form-dataset-page' ...) {
    ...
    $form['submit']['#type'] = 'image_button';
    $form['submit']['#src'] = isset($form_state['pager_plugin']) ? 'profiles/dkan/images/icon-search-27x26.png' : '';
}
```

In cipp.scss, 

``` css
#block-dkan-sitewide-dkan-sitewide-search-bar {
background:#F2F2F2 url(../images/search.png) no-repeat center center !important;}
```

, a different spyglass.

The site-wide search bar has both ids in its tree, so both are applied.
